feat: add styled components, login form
ave-mario/toad pull request #10
Opened 2019-05-28 14:43 UTC by Furmanov19

add styled components, login flow and
login

2019-06-04 06:44 UTC, VikaBondareva commented on src/components/MainPage/index.js
> +      type: 'LOGOUT'
через передачу в mapDispatchToProps

2019-06-04 06:46 UTC, Furmanov19 commented on src/components/MainPage/index.js
> +      type: 'LOGOUT'
пропустил)

2019-06-04 13:46 UTC, eumakarov submitted a review, later dismissed

2019-06-04 14:04 UTC, VikaBondareva submitted a review, later dismissed

2019-06-04 22:15 UTC, underscorekadji requested changes

2019-06-04 22:15 UTC, underscorekadji commented on package.json
> +    "husky:pre-push": "npm run lint:fix",
лучшим вариантом в pre-push скрипте будет проверка линтером без фикса, т.к. фикс ничего не добавит в коммит и запуск тестов, чтобы можно было сказать что со стороны CI/DI ничего не сломается

2019-06-04 22:15 UTC, underscorekadji commented on src/components/LoginPage/view.js
> +export const fakeValidEmail = 'vidgf@sdf.sfn';
Лучше не пушить фейковые данные, если нет необходимого функционала со стороны API, а сразу создавать функционал расчитанный на то, что функционал API может выйти в скором времени или подстроится под реализацию клиента, например.

2019-06-04 22:15 UTC, underscorekadji commented on src/components/LoginPage/view.js
> +export const fakeValidEmail = 'vidgf@sdf.sfn';
Я здесь просто не понимаю зачем `fakeValidEmail` и `fakeValidPassword `

2019-06-04 22:15 UTC, underscorekadji commented on src/sagas/auth.saga.js
> +    if (error.response) {
```suggestion
    const errorMessage = error.response ? error.response.data : error.message
    yield put(Creators.loginFailure(errorMessage));
```

2019-06-05 14:23 UTC, eumakarov submitted a review, later dismissed

2019-06-05 14:28 UTC, VikaBondareva submitted a review, later dismissed

2019-06-06 08:54 UTC, underscorekadji requested changes

2019-06-06 08:54 UTC, underscorekadji commented on src/components/LoginPage/LoginForm.js
> +/* eslint-disable no-shadow */
Отключать eslint - плохо :)

2019-06-06 08:54 UTC, underscorekadji commented on src/components/LoginPage/LoginForm.js
> +    .matches(/^[\S]{5,18}$/, 'The password cannot contain spaces')
я бы вынес regex для пароля в конфигурацию

2019-06-06 08:54 UTC, underscorekadji commented on src/index.js
> +axios.defaults.baseURL = process.env.REACT_APP_API_URL;
так точно нельзя делать

2019-06-07 07:09 UTC, eumakarov submitted a review, later dismissed

2019-06-07 10:19 UTC, VikaBondareva submitted a review, later dismissed

2019-06-10 06:18 UTC, underscorekadji approved these changes

2019-06-10 06:39 UTC, VikaBondareva approved these changes

2019-06-10 06:39 UTC, eumakarov approved these changes

2019-06-10 06:41 UTC, merged